### ISSUE TITLE
Bug: Lua `local function` indentation

### ISSUE THREAD

**Issue by olimorris** [VidocqH/lsp-lens.nvim#14]
I have the following Lua code:

```lua
local function get_commands(filename_prefix)
  return M.split_string(M.read_file(string.format("%s.commands", filename_prefix)), "\n")
end
```

and I noticed that there is a weird indentation which I perceive to be due to `local`:

<img width="782" alt="Screen Shot 2023-03-18 at 13 04 43@2x" src="https://user-images.githubusercontent.com/9512444/226108097-bcd1ee3d-cab1-4e66-816c-b2ce9f52597e.png">

For anything without `local` it works just fine:

<img width="782" alt="Screen Shot 2023-03-18 at 13 05 50@2x" src="https://user-images.githubusercontent.com/9512444/226108125-6db4bc07-184d-4395-b62b-f283a218de53.png">

**Comment by barrett-ruth** [comment]
Bump for this - having the same issue

**Comment by VidocqH** [comment]
I am trying to figure out how to solve it. This is because the Language Server Protocol (LSP) indicates that these functions are starting at this position, and it seems that this only occurs in Lua code.

**Comment by barrett-ruth** [comment]
I see. However, why is the actual column position of the function relevant? Couldn't you just ignore it end set it to 0 (nobody wants a codelens line *not* starting at the beginning of the line)

**Comment by VidocqH** [comment]
> I see. However, why is the actual column position of the function relevant? Couldn't you just ignore it end set it to 0 (nobody wants a codelens line _not_ starting at the beginning of the line)

It's because of indentations, for example:
```cpp
class A {
    // lens starts from this column
    int add(int a, int b) {
        return a + b;
    }
}
```

Maybe I can set it to 0 with Lua file?  Not sure if there is an impact.  :)

**Comment by barrett-ruth** [comment]
Here's a thought - if the server is `lua_ls` *and* the line begins with "local," then set the indentation to 0. What do you think about this solution?

I'd actually like to write a PR for this to code more experience with OSS if that is ok.

**Comment by VidocqH** [comment]
> Here's a thought - if the server is `lua_ls` _and_ the line begins with "local," then set the indentation to 0. What do you think about this solution?
> 
> I'd actually like to write a PR for this to code more experience with OSS if that is ok.

Great! Thank you in advance. I am currently a bit occupied. :)
