### ISSUE TITLE
lsp-lens.nvim does not display anything when there is a declaration on the first line

### ISSUE THREAD

**Issue by kyu08** [VidocqH/lsp-lens.nvim#31]
Hi! Thank you for creating nice plugin! I love your project.

# Problem
As the title says, lsp-lens.nvim does not display anything when there is a declaration on the first line.

<img width="995" alt="image" src="https://github.com/VidocqH/lsp-lens.nvim/assets/49891479/87b7f60b-c4a3-4119-a120-880ab1ffb28a">

When I add comment above the declaration, References and Implements is shown.

<img width="637" alt="image" src="https://github.com/VidocqH/lsp-lens.nvim/assets/49891479/1f042921-5883-4387-a57b-b98e09594fc9">

[Here](https://github.com/kyu08/fzf-make/blob/e05f11ce4bcff145acd87d3190f9d0a1d184f1de/src/usecases/usecase.rs#L1) is the code I used to reproduce it.

# What I expect
I would like to see References and Implements displayed even if there is a declaration on the first line.

I would be very happy if you could consider this when you have time.

**Comment by VidocqH** [comment]
Hi, this is a well-known bug of neovim's `virt_lines_above`, it does not scroll down automatically when the target line is the first line, you can refer to this issue. neovim/neovim#16166  😊

**Comment by kyu08** [comment]
@VidocqH 
I didn't know this behavior is caused by neovim's bug.
Thank you for letting me know that!
