### ISSUE TITLE
implementation should be implements

### ISSUE THREAD

**Issue by xiantang** [VidocqH/lsp-lens.nvim#5]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/34479567/224524342-0b841a71-d28a-4595-9ac2-a41438355946.png">

xxxxManager  is a struct and it implements Manager interface. 
so lsp-lens should  display `Implements:1 | References: 5`

**Comment by xiantang** [comment]
in lspsaga it is also shown as "Implements" and not as "Implementation", I think we have to adapt to lspsaga
<img width="351" alt="image" src="https://user-images.githubusercontent.com/34479567/224526065-188d89c6-493a-4624-8317-46160d465325.png">

**Comment by VidocqH** [comment]
OK, that will be an easy work. I use "implementation" because of the request method 'textDocument/implementation'.
哈哈哈哈哈哈哈哈😂

**Comment by xiantang** [comment]
谢谢你

**Comment by xiantang** [comment]
> OK, that will be an easy work. I use "implementation" because of the request method 'textDocument/implementation'. 哈哈哈哈哈哈哈哈😂

I will contribute the PR

**Comment by VidocqH** [comment]
> > OK, that will be an easy work. I use "implementation" because of the request method 'textDocument/implementation'. 哈哈哈哈哈哈哈哈😂
> 
> I'm willing to contribute the PR

Oh.. I already written it...

**Comment by xiantang** [comment]
ok coool

**Comment by xiantang** [comment]
let me try

**Comment by xiantang** [comment]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/34479567/224526684-8b1df4c9-12e6-40c7-8768-eb965a07ff6a.png">
Looks good
