### ISSUE TITLE
wrong number of references 

### ISSUE THREAD

**Issue by xiantang** [VidocqH/lsp-lens.nvim#8]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/34479567/224529666-51b56ef2-f60c-4813-9dc9-746d2d6a1630.png">

How to reproduce:

1. find a Lua function defined with a module, e.g.: function lsplens:lsp_lens_toggle() 
2. check the references count

should lsp_lens_toggle references count not be lsplens references count

**Comment by VidocqH** [comment]
I also noticed that. Seems like it is caused by the bad request params. I will look at it later.

bad request params exemple
```json
{
  context = {
    includeDeclaration = false
  },
  position = {
    character = 9,
    line = 34
  },
  textDocument = {
    uri = "file:///Users/vidocq/nvim_plugs/lens-nvim/lua/lsp-lens/utils.lua"
  }
}
```
